delete from unidade;

insert into unidade (cd_unidade,nm_unidade) values (1,'CDP Shopping Tamboré');
insert into unidade (cd_unidade,nm_unidade) values (2,'CDP Shopping Mooca');
insert into unidade (cd_unidade,nm_unidade) values (3,'CDP Adolfo Pinheiro');
insert into unidade (cd_unidade,nm_unidade) values (4,'CDP Shop. Aquarios Marilia');
insert into unidade (cd_unidade,nm_unidade) values (5,'CDP Shop. Bauru');
insert into unidade (cd_unidade,nm_unidade) values (6,'CDP Central Plaza');
insert into unidade (cd_unidade,nm_unidade) values (7,'CDP Continental Center');
insert into unidade (cd_unidade,nm_unidade) values (8,'CDP Embu - Loja de Rua');
insert into unidade (cd_unidade,nm_unidade) values (9,'CDP Galeria Comercial');
insert into unidade (cd_unidade,nm_unidade) values (10,'CDP Max Shop. Jundiaí');
insert into unidade (cd_unidade,nm_unidade) values (11,'CDP Shop. Rib. Preto');
insert into unidade (cd_unidade,nm_unidade) values (12,'CDP Osasco Plaza');
insert into unidade (cd_unidade,nm_unidade) values (13,'CDP Plaza Shop. Itu');
insert into unidade (cd_unidade,nm_unidade) values (14,'CDP Shop. Raposo');
insert into unidade (cd_unidade,nm_unidade) values (15,'CDP Shop. Rio Preto');
insert into unidade (cd_unidade,nm_unidade) values (16,'CDP Shop. ABC');
insert into unidade (cd_unidade,nm_unidade) values (17,'CDP Shop. Aricanduva');
insert into unidade (cd_unidade,nm_unidade) values (18,'CDP Shop. Butantã');
insert into unidade (cd_unidade,nm_unidade) values (19,'CDP Shop. Campinas');
insert into unidade (cd_unidade,nm_unidade) values (20,'CDP Shop. Colinas Loja');
insert into unidade (cd_unidade,nm_unidade) values (21,'CDP Shop. Colinas Quiosque');
insert into unidade (cd_unidade,nm_unidade) values (22,'CDP Center III');
insert into unidade (cd_unidade,nm_unidade) values (23,'CDP Shop. WTC ext');
insert into unidade (cd_unidade,nm_unidade) values (24,'CDP Shop. D''&''D int.');
insert into unidade (cd_unidade,nm_unidade) values (25,'CDP Shop. Dom Pedro');
insert into unidade (cd_unidade,nm_unidade) values (26,'CDP Shop. Eldorado');
insert into unidade (cd_unidade,nm_unidade) values (27,'CDP Esplanada Shop.');
insert into unidade (cd_unidade,nm_unidade) values (28,'CDP Frei Caneca');
insert into unidade (cd_unidade,nm_unidade) values (29,'CDP Shopping Galeria');
insert into unidade (cd_unidade,nm_unidade) values (30,'CDP Shop. Granja');
insert into unidade (cd_unidade,nm_unidade) values (31,'CDP Shop. Ibirapuera');
insert into unidade (cd_unidade,nm_unidade) values (32,'CDP Shop. Iguatemi Campinas');
insert into unidade (cd_unidade,nm_unidade) values (33,'CDP Ribeirão Shopping');
insert into unidade (cd_unidade,nm_unidade) values (34,'CDP Shop. Jardim Sul  Terreo');
insert into unidade (cd_unidade,nm_unidade) values (35,'CDP Shop. Jardim Sul  Piso I');
insert into unidade (cd_unidade,nm_unidade) values (36,'CDP Shop. Metrópolis');
insert into unidade (cd_unidade,nm_unidade) values (37,'CDP Shop. Higienópolis');
insert into unidade (cd_unidade,nm_unidade) values (38,'CDP Shop. Limeira');
insert into unidade (cd_unidade,nm_unidade) values (39,'CDP Shop. Piracicaba');
insert into unidade (cd_unidade,nm_unidade) values (40,'CDP Shop. Serra Azul');
insert into unidade (cd_unidade,nm_unidade) values (41,'CDP Shop. Taboao');
insert into unidade (cd_unidade,nm_unidade) values (42,'CDP Shop. União');
insert into unidade (cd_unidade,nm_unidade) values (43,'CDP Shop. Vila Olímpia');
insert into unidade (cd_unidade,nm_unidade) values (44,'CDP Shop. Osasco');
insert into unidade (cd_unidade,nm_unidade) values (45,'CDP Shop. Tivoli');
insert into unidade (cd_unidade,nm_unidade) values (46,'CDP Analia Franco Piso Tulipa');
insert into unidade (cd_unidade,nm_unidade) values (47,'CDP Analia Franco Piso Orquídea');
insert into unidade (cd_unidade,nm_unidade) values (48,'CDP Shop. ABC Plaza');
insert into unidade (cd_unidade,nm_unidade) values (49,'CDP Shop. SP Market');
insert into unidade (cd_unidade,nm_unidade) values (50,'CDP Shop. Santana');
insert into unidade (cd_unidade,nm_unidade) values (51,'CDP Shop. Esplanada');
insert into unidade (cd_unidade,nm_unidade) values (52,'CDP Alphaville');
insert into unidade (cd_unidade,nm_unidade) values (53,'CDP Shop. Itu Plaza');
insert into unidade (cd_unidade,nm_unidade) values (54,'CDP Center Vale');
insert into unidade (cd_unidade,nm_unidade) values (55,'CDP Anália I - Orquídea');
insert into unidade (cd_unidade,nm_unidade) values (56,'CDP Anália II - Tulipa');
insert into unidade (cd_unidade,nm_unidade) values (57,'CDP São Bernardo');
insert into unidade (cd_unidade,nm_unidade) values (58,'CDP Golden Square');
insert into unidade (cd_unidade,nm_unidade) values (59,'CDP Casa Outlet');
insert into unidade (cd_unidade,nm_unidade) values (60,'CDP Iguatemi São José do Rio Preto');
insert into unidade (cd_unidade,nm_unidade) values (61,'CDP Atlântico Center');
insert into unidade (cd_unidade,nm_unidade) values (62,'CDP Shop. Balneário');
insert into unidade (cd_unidade,nm_unidade) values (63,'CDP ParkShop. Barigui');
insert into unidade (cd_unidade,nm_unidade) values (64,'CDP Shop. Paladium');
insert into unidade (cd_unidade,nm_unidade) values (65,'CDP Hiper CenterMS');
insert into unidade (cd_unidade,nm_unidade) values (66,'CDP Shop. Campo Grande');
insert into unidade (cd_unidade,nm_unidade) values (67,'CDP Ramos e Oliveira Comercio de Alimentos Ltda.Me. ');
insert into unidade (cd_unidade,nm_unidade) values (68,'CDP Shop. Barra');
insert into unidade (cd_unidade,nm_unidade) values (69,'CDP Shop. Carioca');
insert into unidade (cd_unidade,nm_unidade) values (70,'CDP Shop. Leblon');
insert into unidade (cd_unidade,nm_unidade) values (71,'CDP Shop. Tijuca');
insert into unidade (cd_unidade,nm_unidade) values (72,'CDP Shopping Metropolitano');
insert into unidade (cd_unidade,nm_unidade) values (73,'CDP Shop. Diammond');
insert into unidade (cd_unidade,nm_unidade) values (74,'CDP Shop. Del Rey');
insert into unidade (cd_unidade,nm_unidade) values (75,'CDP Shop. Uberlandia');
insert into unidade (cd_unidade,nm_unidade) values (76,'CDP Shop. Brasil Park Anápolis');
insert into unidade (cd_unidade,nm_unidade) values (77,'CDP Shop. Goiânia');
insert into unidade (cd_unidade,nm_unidade) values (78,'CDP Shop. Flamboyant');
insert into unidade (cd_unidade,nm_unidade) values (79,'CDP Shopping Paralela');
insert into unidade (cd_unidade,nm_unidade) values (80,'CDP Shop. Iguatemi Maceió');
insert into unidade (cd_unidade,nm_unidade) values (81,'CDP Shop. River');
insert into unidade (cd_unidade,nm_unidade) values (82,'CDP Shop. Natal');
insert into unidade (cd_unidade,nm_unidade) values (83,'CDP Shop. Jaracati');
insert into unidade (cd_unidade,nm_unidade) values (84,'CDP Shop. São Luis');
insert into unidade (cd_unidade,nm_unidade) values (85,'CDP Shop. Rio Anil');
insert into unidade (cd_unidade,nm_unidade) values (86,'CDP Shop. Ilha');
insert into unidade (cd_unidade,nm_unidade) values (87,'CDP Boulevard Belém');
insert into unidade (cd_unidade,nm_unidade) values (88,'CDP 100% Video');
insert into unidade (cd_unidade,nm_unidade) values (89,'CDP Cia. Atlética');
insert into unidade (cd_unidade,nm_unidade) values (90,'CDP Cia. Atlética II');
insert into unidade (cd_unidade,nm_unidade) values (91,'CDP Edif. Connext');
insert into unidade (cd_unidade,nm_unidade) values (92,'CDP Hospital do Bebê');
insert into unidade (cd_unidade,nm_unidade) values (93,'CDP Centro Diagnóstico');
insert into unidade (cd_unidade,nm_unidade) values (94,'CDP Shop. Patio Belém');
insert into unidade (cd_unidade,nm_unidade) values (95,'CDP Shop. Amazonas');
insert into unidade (cd_unidade,nm_unidade) values (96,'CDP Shop. Manauara');
insert into unidade (cd_unidade,nm_unidade) values (97,'CDP C.C. de Omena Michieles Me.');

COMMIT;